---
title: "Course Projects"
description: |
output:
  distill::distill_website 
---

# Project Topic and Aim

## Data for Good

In MAT381E: Introduction to Data Science course, you, as a group of 2, are expected to develop a data science project motivated by one of the topics related to, but not limited to:

* Animals,
* Children, 
* Clean energy,
* Clean water,
* Climate,
* Education,
* Food security,
* Gender equality,
* Good health and well-being,
* Hunger,
* Natural hazards (geophysical (e.g., earthquakes), hydrological (e.g., floods), climatological (e.g., droughts and wildfires), meteorological, or biological (e.g., disease epidemics), 
* Poverty,
* Sustainable & accessible cities and communities,
* Responsible consumption & production,
* Reduced inequalities & refugees,
* Peace & justice & human rights, and
* People with disabilities.

Some of these topics are also within the scope of sustainable development goals of United Nations for a better future for our world:

https://www.un.org/sustainabledevelopment/sustainable-development-goals/. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/0XTBYMfZyrM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Feel free to ask for help from your peers who have domain knowledge and data expertise on these topics (and of course, do not forget to thank them at the end of your project).

The main aim of developing a project is to find an open-source data related to the topics mentioned above and then to use basic data science tools (data importing, cleaning, re-shaping, exploring, and visualization techniques) to touch one of societal problems in our world and let their voice be heard by people via posting your project on the web (e.g., GitHub pages). 

# Project Design and Submission Guideline

Throughout the semester, you will submit your project to [GitHub organization of our class](https://github.com/MAT381E-Fall21) at three main stages: 

<ol>
<li> [Project proposal](https://github.com/MAT381E-Fall21/Project_Proposal), 
</li>
<li> [Project interim report](https://github.com/MAT381E-Fall21/project_interim_report), and  
</li>
<li> [Project final report, oral presentation, and project web site at GitHub pages](https://github.com/MAT381E-Fall21/Project_final_report).  
</li>
</ol>

Please, follow the GitHub classroom invitations, which enables you to create your team-based project repository on our [GitHub organization of our class](https://github.com/MAT381E-Fall21), to see the template files which gives you more guideline on how to prepare your report. 

Lastly, you will publish your final project on GitHub pages of our course's GitHub organization. For now, take a look at what GitHub pages is:

<iframe width="560" height="315" src="https://www.youtube.com/embed/2MsN8gpT6jY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Project Team Information

Fall21 semester project team members and their project titles are listed below. 

| Name    | GitHub User Name  | Team Name     | Project GitHub Pages link      |                                                                                                                                   
| --------| -------- | ---------| --------------------------- |
| Çağrı   Gökpunar     | mpospirit         | ananas     | [Relationship between Crime Rates and Income Levels](https://mpospirit.github.io/project_final_report-ananas) |
| Melisa     Kütük        | kutukm17          | ananas       | [Relationship between Crime Rates and Income Levels](https://mpospirit.github.io/project_final_report-ananas) |
| Semih    Atalay       | semihatalay       | atakar        | [Statistics of women and men in education in Turkey](https://karakasm.github.io/MAT381E-Fall21-final-project_atakar/)                                |
| Mahmud Turab   Karakaş      | karakasm          | atakar        | [Statistics of women and men in education in Turkey](https://karakasm.github.io/MAT381E-Fall21-final-project_atakar/)  
| Beyzanur     Ermiş        | beyzaermis        | FireFighter   | [Forest Fires in Turkey](https://beyzaermis.github.io/DataScience_FireFighter/)  |          
| Ayşim         Hırdan       | aysimh            | FireFighter  | [Forest Fires in Turkey](https://beyzaermis.github.io/DataScience_FireFighter/)  |             
| Zeynep    Akkoç        | akkocz17          | Hypatia       |  [Recycling Movement in the World](https://mat-381e-project-team.github.io/Final_Report_Hypatia/)  |                                  
| Selin    Duman        | Selinduman        | Hypatia       | [Recycling Movement in the World](https://mat-381e-project-team.github.io/Final_Report_Hypatia/)  |                                  
| Büşra    Köksal       | bkksl             | Hypatia       | [Recycling Movement in the World](https://mat-381e-project-team.github.io/Final_Report_Hypatia/)  |                                  
| Fevzi   Kaya         | fevzikaya7 | Indian Fellas |  [Effects of Climate Changes in the Indian Ocean on Australia and South Africa](https://fevzikaya7.github.io/final_report_indian_fellas/)                                            |
| Halil  Serdar       | halilserdar       | Indian Fellas | [Effects of Climate Changes in the Indian Ocean on Australia and South Africa](https://fevzikaya7.github.io/final_report_indian_fellas/)                                            |
| Eda   Atalay       | edaatalay         | Melange Team  |      [Analysis of Greenhouse Gas Emissions](https://beyzakebeli.github.io/beyzakebeli-Analysis-of-Greenhouse-Gas-Emissions/) |
| Beyza Nur   Kebeli       | beyzakebeli       | Melange Team  | [Analysis of Greenhouse Gas Emissions](https://beyzakebeli.github.io/beyzakebeli-Analysis-of-Greenhouse-Gas-Emissions/) |
| Uğurcan   Bayraktar    | ugurcanbayraktar  | NA            |    [Statistics of earthquake hazards in Turkey and comparison with the world ](https://ugurcanbayraktar.github.io/DataScience_NA/)                                                          |
| Furkan   Eskicioğlu   | furkanesk         | NA            |  [Statistics of earthquake hazards in Turkey and comparison with the world ](https://ugurcanbayraktar.github.io/DataScience_NA/)             
| Duygu     Kaya         | duygukaya99       | Nazar Boncugu |  [Producing Food While Restoring the Planet](https://duygukaya99.github.io/projectfinal-nazarboncugu/)                                               |
| Görkem      Erarslan     | gorkemerarslann   | Nazar Boncugu | [Producing Food While Restoring the Planet](https://duygukaya99.github.io/projectfinal-nazarboncugu/)                                               |
| İbrahim Talha  Özdemir      | ozdemiri18        | Nazar Boncugu | [Producing Food While Restoring the Planet](https://duygukaya99.github.io/projectfinal-nazarboncugu/)                                               |
| Selin Durmuş       | durmuselin        | noobs         | [Refugee Migration Around The World](https://xemreozkaya.github.io/final-report-noobs/)  |                                                            |
| Yunus Emre   Özkaya       | xemreozkaya       | noobs         | [Refugee Migration Around The World](https://xemreozkaya.github.io/final-report-noobs/)  |                                                              |
| Samet      Saydam       | saydamsamet       | noobs         |   [Refugee Migration Around The World](https://xemreozkaya.github.io/final-report-noobs/)  |                                                       
| Semih   Çetin        | semihctn          | OMS           |  [Turkey Covid-19 and Vaccination Statistics](https://semihctn.github.io/MAT381E-OMS-PROJECT/)  |                                                             
| Serdar Eren  Mersin       | 0SAM10            | Panthers      |           [An Analysis on Endangered and Extinct Fauna and Flora](https://0sam01.github.io/project_final_panthers.html)                                                     |
| Kaan        Kaymaz       | Kaankaymaz        | poverty       | [Child Poverty in the World ](https://alialperenusta.github.io/MAT381E_final_poverty/)   |
| Ali Alperen   Usta         | alialperenusta    | poverty       |   [Child Poverty in the World ](https://alialperenusta.github.io/MAT381E_final_poverty/) |     
| Şeymanur  Ergezgin     | seymaergezgin     | readme     | [OECD Countries' Social and Welfare Statistics and Turkey’s position](https://seymaergezgin.github.io/readme/#)    |                                                                                                                        
| Ecenur    Özsoy        | ecenurozsy        | readme        | [OECD Countries' Social and Welfare Statistics and Turkey’s position](https://seymaergezgin.github.io/readme/#)    |                 
| Berkay      Ocak         | berkayocak9       | riskteam | [Crisis and disaster risks around the world](https://ozgenezgi.github.io/RiskTeam/)|                                                                                     
| Ezgi         Özgen        | ozgenezgi         | riskteam      | [Crisis and disaster risks around the world](https://ozgenezgi.github.io/RiskTeam/)|            
| Oğuzhan    Koç          | koco17            | Shining Stars | Audience Ratios of the Theater Plays by Stage                                |                                                                                                                                                                    |
| Merve         Zengin       | mrvzng7           | Shining Stars | Audience Ratios of the Theater Plays by Stage                                |                                                                                                                                                                    |
| Yaren       Benhür       | yarenbenhur       | Solar Bears   | Statistics of Energy Mix and Renewable Energy Adaptation                     |                                                                                                                                                                    |
| Kenan Baran  Marap        | bmarap            | Solar Bears   | Statistics of Energy Mix and Renewable Energy Adaptation                     | 
| Koray   Küçük        | koraykck          | K-Team       |[Analysis of Clean Water, Sanitation and Hygiene Data in the World](https://koraykck.github.io/project_final_report_K-Team/)|  
| Gizem   Miçooğulları | micoogullarigizem | GDM  |[Analysis of stock market data of vaccine companies in COVID19 pandemic](https://micoogullarigizem.github.io/Project-final-report-gdm/) |
| Yasin Doğa   Özkütük      | dogaozktk         | GDM      |[Analysis of stock market data of vaccine companies in COVID19 pandemic](https://micoogullarigizem.github.io/Project-final-report-gdm/) | 
| Mert   Taşdemir     | merttsdmr         | GDM           | [Analysis of stock market data of vaccine companies in COVID19 pandemic](https://micoogullarigizem.github.io/Project-final-report-gdm/) | 
                                                                                                     

